# Generated by Django 6.0.5 on 2026-10-04 20:23

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_address_description_alter_address_postal_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[accounts.models.validate_national_id]),
        ),
    ]
