# Generated by Django 6.0.5 on 2026-10-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_national_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activity_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='coach_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
