# Generated by Django 6.0.7 on 2026-08-27 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='media',
        ),
        migrations.AddField(
            model_name='media',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='operations.content'),
        ),
    ]
