# Generated by Django 6.0.5 on 2026-09-01 19:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_remove_content_media_media_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationform',
            name='file',
        ),
        migrations.CreateModel(
            name='SubmitConsultationForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='operations.consultationform')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_submissions', to='operations.linemember')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('file', models.FileField(upload_to='')),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form', to='operations.consultationform')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form', to='operations.submitconsultationform')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='submitconsultationform',
            constraint=models.UniqueConstraint(fields=('consultation', 'member'), name='unique_consultation_member_submission'),
        ),
    ]
