# Generated by Django 6.0.5 on 2026-09-03 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_remove_consultationform_file_submitconsultationform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='conversation',
            field=models.OneToOneField(blank=True, help_text='گفتگوی اختصاصی برای این سابمیشن', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission', to='operations.conversation'),
        ),
    ]
