# Generated by Django 6.0.7 on 2026-10-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_assignmentsubmission_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='is_required_assignment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='line',
            name='is_required_content',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='line',
            name='is_required_form',
            field=models.BooleanField(default=True),
        ),
    ]
