# Generated by Django 6.0.7 on 2026-10-04 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_line_is_required_assignment_line_is_required_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentrecipient',
            name='conversation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_recipient', to='operations.conversation'),
        ),
    ]
