# Generated by Django 6.0.7 on 2026-10-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_contentrecipient_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='is_required_appointment',
            field=models.BooleanField(default=True),
        ),
    ]
