# Generated by Django 6.0.5 on 2026-09-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('contact_type', models.CharField(choices=[('phone', 'تلفنی'), ('messenger', 'پیام\u200cرسان'), ('email', 'ایمیل')], max_length=20)),
                ('messenger_type', models.CharField(blank=True, choices=[('whatsapp', 'واتساپ'), ('telegram', 'تلگرام'), ('eitaa', 'ایتا'), ('rubika', 'روبیکا'), ('bale', 'بله')], max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
